name: 🙋‍♂️ [SproutDiary] - Support & Feedback
description: "Get help with SproutDiary, report bugs or request new features."
title: '🙋‍♂️ Support & Feedback: SproutDiary'
labels: ['support', 'feedback', 'question']
assignees:
  - jaywcjlove

body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="100" alt="SproutDiary" src="https://github.com/user-attachments/assets/965f303e-1c75-4a08-afc1-565ed5b9c06b" />
        Please provide your support request or feedback in detail.

        SproutDiary is designed for new parents to record babies' daily information, feeding details, physical status and growth data. Traditional paper notes and memo apps cause scattered records, inconvenient search, difficult statistics and unclear growth tracking.
        This app integrates all recording demands from birth to growth period. It helps parents systematically keep precious growth memories, provides accurate historical data for physical examinations and medical visits, and eases daily recording burden.

        ### Contact Information

        Feel free to reach out if you encounter any issues or need assistance:

        - **Email Support**: [hy963132341@gmail.com](mailto:hy963132341@gmail.com)
        - **Social Media**: [Twitter](https://twitter.com/hx_yii)

        We will reply to you as soon as possible. Thank you for your support!

  - type: textarea
    attributes:
      label: 🙋‍♂️ What help do you need?
      description: Describe your encountered problem or feature request.
      placeholder: For example, I found an issue...
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "📱 Device System"
      description: Your device system and version.
      options:
        - iPhone
        - Android
        - Web
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **How to submit app crash reports?**

        - Capture screenshots or record bug videos
        - Compress files into a ZIP package
        - Attach the file to this issue

  - type: textarea
    attributes:
      label: ℹ️ Additional Information
      description: Add extra details about your problem.
      placeholder: Such as screenshots, reproduction steps, etc.
    validations:
      required: false