blank_issues_enabled: false
contact_links:
  - name: 🌐 SproutDiary Official Website
    url: https://github.com/hy916/SproutDiary
    about: Introduction to the SproutDiary app on the official website!